### ISSUE TITLE
Shadow Background picker shows black background preview palette in Customizer

### ISSUE THREAD

**Issue by aryanrajseo** [seothemes/genesis-customizer-theme#1]
Base Styles > Global. Drop Shadow preview background became black while selecting some background color from color palette.

Found same shadow issue on 

- Base styles > Buttons. 
- Header > Primary Header shadow.
- Sidebars > Primary sidebars
- Sidebars > Secondary Sidebars

![2019-04-01 18-32-10 2019-04-01 18_34_11](https://user-images.githubusercontent.com/34836534/55337419-446ba180-54bc-11e9-8181-b8fc438881c9.gif)

**Comment by seothemes** [comment]
Fixed with hardcoded CSS to force the background color.
