### ISSUE TITLE
Remove Hero section default Background settings from free version

### ISSUE THREAD

**Issue by aryanrajseo** [seothemes/genesis-customizer-theme#3]
Hero Section having Default Background settings option should be removed from free version. 

If it should be present, not found any option to enable this and so This is not working on free version.

![2019-04-01 20-33-30 2019-04-01 20_33_52](https://user-images.githubusercontent.com/34836534/55338083-8517ea80-54bd-11e9-9e83-73772dafaf11.gif)

**Comment by seothemes** [comment]
Fixed. There is now a check to see if Pro is active before adding this section.
