### ISSUE TITLE
Section Colors & typography and reverting to default or old settings

### ISSUE THREAD

**Issue by aryanrajseo** [seothemes/genesis-customizer-theme#4]
So, I was taking a closer look on some sections and found an important bug which need to be fixed.

**The mistake.**

Every time i visit any section in Genesis Customizer, I add/modify colors/typography and other things and clicks PUBLISH. I was clicking on PUBLISH button on each section i was working on.

**Section Colors  are not saving.**
Each section includes various Colors customization option. However, After adding these colors value, we go to some settings like  Content Area > Author Box and put some title value it will revert the default settings and colors. Here we have forgot to PUBLISH/save that section changes.

https://genesiscustomizer.slack.com/archives/CH4JANP2R/p1554132996007500

**Section Typography are revert to default or older one.**
Same bug with typography too. Going back from a section(where you made some changes and not clicked the publish button on that section) to a different section and made some changes that reloads, fetch from backend like featured image, custom value output from php reverts the section settings to default or old what was last saved.

https://genesiscustomizer.slack.com/archives/CH4JANP2R/p1554133124007900

I got this in my mind while writing this(below) bug.

**Custom Title in Author Box removes Custom Colors**
Content Area > Author Box. Added custom colors for Background, Title and content. Now typed a different title and now custom Colors reverted back to default or older one. First time only/

Anything that takes the title value from backend/php. 

See video screenshot carefully.

You understand this.
SOrry, I am not good in explaining this but hope you get this.

**Comment by aryanrajseo** [comment]
I assume this may be the same reason Anita carter was not able to see those changes she had made on her test site. because she not published each section colors/typography settings.

**Comment by aryanrajseo** [comment]
This may also issue related with some section colors reverting to defaults i mentioned in earlier version of bug reports.

**Comment by seothemes** [comment]
Fixed by outputting inline CSS when in the Customizer, and a stylesheet when on the front end.
