### ISSUE TITLE
Broken Footer Widgets Layouts

### ISSUE THREAD

**Issue by aryanrajseo** [seothemes/genesis-customizer-theme#6]
Footer > Footer Widgets.
3rd and 4th  Columns layout type is broken.  
![image](https://user-images.githubusercontent.com/34836534/55344577-530d8500-54cb-11e9-9d61-26ed7c6dfeb4.png)

I see invalid property value warning in CSS
![image](https://user-images.githubusercontent.com/34836534/55344489-15a8f780-54cb-11e9-934f-e21df2cbfa83.png)

**Comment by seothemes** [comment]
Fixed in plugin
